filter:
  excluded_paths:
    - 'tests/*'

build:
  environment:
    php: '7.2.13'
  nodes:
    dependencies:
      override:
        - composer --prefer-dist --no-suggest --no-interaction
    analysis:
      tests:
        override:
          - command: 'vendor/bin/phpinsights analyse ./src/ --format=checkstyle --no-interaction > analysis-phpinsights.xml'
            analysis:
              file: 'analysis-phpinsights.xml'
              format: 'general-checkstyle'
